apiVersion: v1 
kind: Pod 
metadata: 
  name: {{ .Name }} 
  namespace: {{ .Namespace }} 
spec: 
  containers: 
  - name: {{ .Container.Name }} 
    image: {{ .Container.Image}} 
    resources: 
      limits: 
        memory: "{{ .Container.Resource.Memory }}" 
